name: product_viewer
description: "Demo Flutter project for Aktin interview"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.5
  bloc: ^8.1.4
  http: ^1.2.2
  stream_transform: ^2.1.0
  internet_connection_checker: ^2.0.0
  flutter_rating: ^2.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.1
  get_it: ^8.0.0
  toastification: ^2.2.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1

flutter_lints: ^4.0.0
flutter:
  uses-material-design: true